services:
  web:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/src
    depends_on:
      - app

  app:
    container_name: php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  db:
    container_name: mysql
    image: mysql:8.0.38
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=${MYSQL_ROOT_PASSWORD}"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
  
  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - 6379:6379